spring:
  application:
    name: OAuth2 Facebook  main:    allow-bean-definition-overriding: true
    
security:  oauth2:    client:
      client-id: ###############
      client-secret: ##############################
      access-token-uri: https://graph.facebook.com/v7.0/oauth/access_token
      user-authorization-uri: https://www.facebook.com/v7.0/dialog/oauth
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form    resource:      user-info-uri: https://graph.facebook.com/me