server:
  port: 8082
  servlet:    context-path: /ui    session:      cookie:        name: UISESSION

security:  oauth2:    client:      client-id: ClientId         # ClientId as given to the clientDetails at resource/server
      client-secret: secret       # secret key as given to the clientDetails at resource/server
      access-token-uri: http://localhost:8081/auth/oauth/token
      user-authorization-uri: http://localhost:8081/auth/oauth/authorize
    resource:      user-info-uri: http://localhost:8081/rest/hello/principal
      
spring:  thymeleaf:    cache: false  application:    name: Oauth Client